name: Merge Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
permissions:
  issues: write
  pull-requests: write

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for disallowed files and directories
        id: check_files
        run: |
          if git diff --name-only origin/main...HEAD | grep -E 'node_modules/'; then
            echo "🚨 node_modules folder detected. Please remove it." > disallowed_files.txt
            echo "disallowed_files_present=true" >> $GITHUB_OUTPUT
          fi
          if git diff --name-only origin/main...HEAD | grep -E *.txt; then
            echo "🚨 txt files detected. Please remove them." > disallowed_files.txt
            echo "disallowed_files_present=true" >> $GITHUB_OUTPUT
          fi

      - name: Comment PR on disallowed files failure
        if: steps.check_files.outputs.disallowed_files_present == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const disallowedFiles = fs.readFileSync('disallowed_files.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              body: disallowedFiles,
              repo: context.repo.repo,
              owner: context.repo.owner,
            });
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail if disallowed files are present
        if: steps.check_files.outputs.disallowed_files_present == 'true'
        run: exit 1

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint and Prettier
        id: lint_and_prettify
        run: |
          npm run lint > eslint-output.txt || echo "eslint_failed=true" >> $GITHUB_OUTPUT
          npm run format || echo "prettify_failed=true" >> $GITHUB_OUTPUT

      - name: Comment PR on ESLint/Prettier failure
        if: steps.lint_and_prettify.outputs.eslint_failed == 'true' || steps.lint_and_prettify.outputs.prettify_failed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const eslintOutput = fs.readFileSync('eslint-output.txt', 'utf8');
            const message = `🚨 Lint/Prettier issues found:\n\n\`\`\`\n${eslintOutput}\n\`\`\`\nPlease fix the issues.`;
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              body: message,
              repo: context.repo.repo,
              owner: context.repo.owner,
            });
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail if lint or prettier failed
        if: steps.lint_and_prettify.outputs.eslint_failed == 'true' || steps.lint_and_prettify.outputs.prettify_failed == 'true'
        run: exit 1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        id: run_tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_FILE: test_output.log
        run: |
          npm run test:cicd > test_output.log 2>&1 || echo "test_failed=true" >> $GITHUB_OUTPUT

      - name: Comment PR on test failure
        if: steps.run_tests.outputs.test_failed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const testLog = fs.readFileSync('test_output.log', 'utf8');
            const message = `🚨 Vitest tests failed. Check the logs:\n\n\`\`\`\n${testLog}\n\`\`\``;
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              body: message,
              repo: context.repo.repo,
              owner: context.repo.owner,
            });
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail if tests failed
        if: steps.run_tests.outputs.test_failed == 'true'
        run: exit 1